manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: george-norton
      url-base: https://github.com/george-norton
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-driver-pmw3360
      remote: george-norton
      revision: main

    - name: zmk-hid-trackball-interface
      remote: englmaxi
      revision: main

  self:
    path: config
